# Generated by Django 5.0.3 on 2024-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=60)),
                ('varsta', models.IntegerField()),
                ('gen', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('specie', models.CharField(choices=[('caine', 'Caine'), ('pisica', 'Pisica'), ('iepure', 'Iepure')], max_length=6)),
            ],
        ),
    ]
